### ISSUE TITLE
Wont run OOB on debian stretch. 

### ISSUE THREAD

**Issue by Chrs2021** [thesparklabs/openvpn-configuration-generator#2]
Trying to run this on debian stretch i am getting a lot of library missing errors. to make this tool easier would it be better to statically link the releases or provide a make file to build this on our own.

**Comment by trametheka** [comment]
Hi Chrs2021,

The tool is built on Swift, which is only officially built for Ubuntu at the moment and would be the problem here. You could possibly compile Swift yourself and replace the Swift libraries included with the deb bundle yourself, but this would be a mammoth task.

At the moment, we only support Ubuntu x64 16.04 I'm afraid.
